apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-aggregate-prometheus=allowed'
      to all the shoot apiservers running in the seed cluster.
  name: allow-to-aggregate-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-aggregate-prometheus: allowed
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: aggregate-prometheus
          role: monitoring
  policyTypes:
  - Egress
  ingress: []