groups:
- name: kube-state-metrics.rules
  rules:
  - alert: KubeStateMetricsShootDown
    expr: absent(up{job="kube-state-metrics", type="shoot"} == 1)
    for: 15m
    labels:
      service: kube-state-metrics-shoot
      severity: info
      visibility: operator
      type: seed
    annotations:
      summary: Kube-state-metrics for shoot cluster metrics is down.
      description: There are no running kube-state-metric pods for the shoot cluster. No kubernetes resource metrics can be scraped.

  - alert: KubeStateMetricsSeedDown
    expr: absent(up{job="kube-state-metrics", type="seed"} == 1)
    for: 15m
    labels:
      service: kube-state-metrics-seed
      severity: critical
      visibility: operator
      type: seed
    annotations:
      summary: Kube-state-metrics for seed cluster metrics is down.
      description: There are no running kube-state-metric pods for the seed cluster. No kubernetes resource metrics can be scraped.

  - alert: NoWorkerNodes
    expr: sum(kube_node_spec_unschedulable) == count(kube_node_info) or absent(kube_node_info)
    for: 25m # MCM timeout + grace period to allow self healing before firing alert
    labels:
      service: nodes
      severity: blocker
      visibility: all
    annotations:
      description: There are no worker nodes in the cluster or all of the worker nodes in the cluster are not schedulable.
      summary: No nodes available. Possibly all workloads down.

  - record: shoot:kube_node_status_capacity_cpu_cores:sum
    expr: sum(kube_node_status_capacity_cpu_cores)

  - record: shoot:kube_node_status_capacity_memory_bytes:sum
    expr: sum(kube_node_status_capacity_memory_bytes)

  - record: shoot:machine_types:sum
    expr: sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type)

  - record: shoot:node_operating_system:sum
    expr: sum(kube_node_info) by (os_image, kernel_version)