groups:
- name: kube-etcd3.rules
  rules:
  # alert if main etcd is down
  - alert: KubeEtcdMainDown
    expr: sum(up{job="kube-etcd3",role="main"}) < 1
    for: 5m
    labels:
      service: etcd
      severity: blocker
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 cluster main is unavailable or cannot be scraped. As long as etcd3 main is down the cluster is unreachable.
      summary: Etcd3 main cluster down.
  # alert if events etcd is down
  - alert: KubeEtcdEventsDown
    expr: sum(up{job="kube-etcd3",role="events"}) < 1
    for: 15m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 cluster events is unavailable or cannot be scraped. Cluster events cannot be collected.
      summary: Etcd3 events cluster down.
  # etcd leader alerts
  - alert: KubeEtcd3MainNoLeader
    expr: sum(etcd_server_has_leader{job="kube-etcd3",role="main"}) < count(etcd_server_has_leader{job="kube-etcd3",role="main"})
    for: 10m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 main has no leader. No communication with etcd main possible. Apiserver is read only.
      summary: Etcd3 main has no leader.
  - alert: KubeEtcd3EventsNoLeader
    expr: sum(etcd_server_has_leader{job="kube-etcd3",role="events"}) < count(etcd_server_has_leader{job="kube-etcd3",role="events"})
    for: 15m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 events has no leader. No communication with etcd events possible. New cluster events cannot be collected. Events can only be read.
      summary: Etcd3 events has no leader.

  ### etcd proposal alerts ###
  # alert if there are several failed proposals within an hour
  # Note: Increasing the failedProposals count to 80, known issue in etcd, fix in progress
  # https://github.com/kubernetes/kubernetes/pull/64539 - fix in Kubernetes to be released with v1.15
  # https://github.com/etcd-io/etcd/issues/9360 - ongoing discussion in etcd
  # TODO (shreyas-s-rao): change value from 120 to 5 after upgrading to etcd 3.4
  - alert: KubeEtcd3HighNumberOfFailedProposals
    expr: increase(etcd_server_proposals_failed_total{job="kube-etcd3"}[1h]) > 120
    labels:
      service: etcd
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 pod {{ $labels.pod }} has seen {{ $value }} proposal failures
        within the last hour.
      summary: High number of failed etcd proposals

  # etcd DB size alerts
  - alert: KubeEtcd3DbSizeLimitApproaching
    expr: (etcd_mvcc_db_total_size_in_bytes{job="kube-etcd3"} > bool 7516193000) + (etcd_mvcc_db_total_size_in_bytes{job="kube-etcd3"} <= bool 8589935000) == 2 # between 7GB and 8GB
    labels:
      service: etcd
      severity: warning
      type: seed
      visibility: all
    annotations:
      description: Etcd3 {{ $labels.role }} DB size is approaching its current practical limit of 8GB. Etcd quota might need to be increased.
      summary: Etcd3 {{ $labels.role }} DB size is approaching its current practical limit.

  - alert: KubeEtcd3DbSizeLimitCrossed
    expr: etcd_mvcc_db_total_size_in_bytes{job="kube-etcd3"} > 8589935000 # above 8GB
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: all
    annotations:
      description: Etcd3 {{ $labels.role }} DB size has crossed its current practical limit of 8GB. Etcd quota must be increased to allow updates.
      summary: Etcd3 {{ $labels.role }} DB size has crossed its current practical limit.

  # etcd backup failure alerts
  - alert: KubeEtcdDeltaBackupFailed
    expr: (time() - etcdbr_snapshot_latest_timestamp{job="kube-etcd3-backup-restore",kind="Incr",role="main"} > bool 900) + (etcdbr_snapshot_required{kind="Incr", role="main"} >= bool 1) == 2
    for: 15m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: No delta snapshot for the past at least 30 minutes.
      summary: Etcd delta snapshot failure.
  - alert: KubeEtcdFullBackupFailed
    expr: (time() - etcdbr_snapshot_latest_timestamp{job="kube-etcd3-backup-restore",kind="Full",role="main"} > bool 86400) + (etcdbr_snapshot_required{kind="Full", role="main"} >= bool 1) == 2
    for: 15m
    labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
    annotations:
        description: No full snapshot taken in the past day.
        summary: Etcd full snapshot failure.

  # etcd data restoration failure alert
  - alert: KubeEtcdRestorationFailed
    expr: rate(etcdbr_restoration_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",succeeded="false"}[2m]) > 0
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd data restoration was triggered, but has failed.
      summary: Etcd data restoration failure.

  - record: shoot:etcd_object_counts:sum_by_resource
    expr: sum(etcd_object_counts) by (resource)